---
title: "Stats problems"
output:
  html_document:
    theme: "cerulean"
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  pdf_document:
    toc: true
---

# Intro
Was looking at a job posting that had some stats questions in the application form. Thought I would show my work here, rather than trying to cram it into the answer field.

# Bruises and Burns
This is a pretty straightforward application of Baye's theorem.

We want the probability that an injury is a burn ($P(bu|s)$) or a bruise ($P(br|s)$) given that some swelling has been observed. These are given by Baye's rule:
$$
\begin{aligned}
P(bu|s) &=& \frac{P(s|bu)\,P(bu)}{P(s)} \\
P(br|s) &=& \frac{P(s|br)\,P(br)}{P(s)} \\
\end{aligned}
$$

Of observed injuries, bruises occur with a frequency of 0.1 and burns occur with a frequency of 0.01. These are the __Prior__ probabilities:
$$
\begin{aligned}
P(bu) & = & 0.01 \\
P(br) & = & 0.1 
\end{aligned}
$$

We also know the conditional probabilities that swelling will occur in the case of a bruise or burn:

$$
\begin{aligned}
P(s|bu) & = & 0.05 \\
P(s|br) & = & 0.3
\end{aligned}
$$

Finally, as far as we know, swelling only occurs in bruises and burns (no other types of injuries). Thus the probability of sweelling occuring (our evidence) is
$$
\begin{aligned}
P(S) & = & P(s|bu)P(bu) + P(s|br) P(br) \\
& = & 0.3 \times 0.01 + 0.05 \times 0.1 \\
& = & 0.008
\end{aligned}
$$

The posterior probabilities are then
$$
\begin{aligned}
P(bu|s) & = & \frac{0.05 \times 0.1}{0.008} & = & 0.625 \\
P(br|s) & = & \frac{0.3 \times 0.01}{0.008} & = & 0.375
\end{aligned}
$$
Thus, given the swelling, it is most likely that the injury is a burn (62.5%)

# Number of Bruises

Given 6 injuries that exhibit swelling we want to know the probability that at least two are bruises.

The probability of $k$ bruises occuring from $n$ swelling incidences is given by the binomial distribution
$$ 
P(k,n) = \binom{n}{k} p^k \, (1 - p)^{n-k}
$$
where p is the probability of a bruise occuring (P(br|s))

The probabilty of at least 2 bruises occuring can be found by summing $P(k,n)$ for $2 \leq k \leq 6$.
This is more math than I care to do on paper right now, so Python:

```{python}

from scipy.misc import comb
ProbBruiseSwell = 0.375

def ProbKBruises(k,N=6):
   prob = comb(N=N,k=k) * (ProbBruiseSwell**k) * (1 - ProbBruiseSwell)**(N - k)
   return prob

sum =0
for k in range(2,7):
    kprob = ProbKBruises(k)
    print('probability of {k} bruises = {prob:5.3f}'.format(k=k,prob=kprob))
    sum += kprob
print('Probability of at least 2 bruises = {p2:5.3f}'.format(p2=sum))

```

There is a 73.6% chance of at least 2 bruises occuring from 6 swellings.

# Gumballs

There are 10 red gumballs and 5 green. The probability of drawing r,r,g,g,g is 
$$
\begin{aligned} 
P(rrggg) & = & \frac{10}{15} \times \frac{9}{14} \times \frac{5}{13} \times \frac{4}{12} \times \frac{3}{11} \\
& = & \frac{5400}{360360}\\
& = & 30/2002\\
& = & 0.015
\end{aligned}
$$
This is a specific ordering, but drawing the same combination in a different order would yield the same probability. The ordering of the numerators in the above expression would change (the denominators would not), but multiplication is commutative so the result is the same. Now we need to know how many different orderings (permuations) of two red and three green balls exist. There are $\binom{5}{2}$ of these.

thus
$$
\begin{aligned}
P(2r,3g) & = & \binom{5}{2} \, \frac{30}{2002} \\
& = & \frac{5!}{2!3!} \frac{30}{2002}\\
& = & 300/2002 \\
& = & 0.150
\end{aligned}
$$

There is a 15% chance of drawing 2 red gumballs and 3 green.

Sanity check: Do the probabilities for 1-5 red balls sum to 1?
```{python}

bagRed = 10
bagGreen = 5
draw = 5

from scipy.misc import comb

def drawRedBalls(nred):
    '''compute the probability of drawing 5 balls, with nred red, in a specific red-green order
    Will multiply individual drawing probabilities rather than using combinatorics and factorials
    This avoids potential overflows from multiplying large integers, and should be easier to follow. 
    '''
    bag = (bagRed + bagGreen)*1.0
    prob = 1.0

    # draw red first
    for ired in range(0,nred):
        prob *= (bagRed - ired)/bag
        bag -= 1

    # draw green
    for igreen in range(0,draw - nred):
        prob *= (bagGreen - igreen)/bag
        bag -=1
    # print('probability to draw {k} red balls from {nd} in a specific order = {p}'.format(k=nred,nd=draw,p=prob))

    # multiply by the number of red/green order permutations
    prob *= comb(N=draw,k=nred)
    # print('summed over orderings = {p}'.format(p=prob))
    return(prob)

# compute 

sumProb = 0.0
for nr in range(0,6):
    RBprob = drawRedBalls(nr)
    sumProb += RBprob
    print('prob of drawing {i} red: {p:6.4f}'.format(i=nr,p=RBprob))

print('total probability: {s:6.4f}'.format(s=sumProb))
```



<!-- 

5 choose 2
5! / 3! 2! = 120/6/2 = 10
rrggg
rgrgg
rggrg
rgggr
grrgg
grgrg
grggr
ggrrg
ggrgr
gggrr

4 +2 -1
2
 -->

